WIDTH = 21
HEIGHT = 18
snakes_hamiltonian_cycle = [ 
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,  LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  UP,]



WIDTH = 30
HEIGHT = 30
snakes_hamiltonian_cycle = [DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, DOWN, UP,
DOWN, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, UP,
RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, RIGHT, UP]



WIDTH = 11
HEIGHT = 10
snakes_hamiltonian_cycle = [ 
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  UP]

WIDTH = 21
HEIGHT = 20
snakes_hamiltonian_cycle = [ 
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,  LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  UP,]