
# reversed
snakes_hamiltonian_cycle = [ 
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  DOWN,   UP,
DOWN,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   LEFT,   UP,
RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  RIGHT,  UP,
]
